# At Time : Fri May 15 00:19:15 2020
# Python 2.7
# -*- coding: utf-8 -*-
# coding=utf-8
import urllib, os, sys
import time
red = '\x1b[1;91m'
green = '\x1b[1;92m'
yellow = '\x1b[1;93m'
blue = '\x1b[1;94m'
purple = '\x1b[1;95m'
cyan = '\x1b[1;96m'
white = '\x1b[1;97m'


####SLOWPRINT####
def slowprint(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(0.1 / 100)

def slowprint2(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(6.0 / 100)

def main():
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m Virus droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m vIrus droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viRus droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virUs droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viruS droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus dRoid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus drOid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droId creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droiD creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid Creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid cReators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid crEators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creAtors ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creaTors ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatOs .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatoRs ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creatorS ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m Virus droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m vIrus droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viRus droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virUs droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viruS droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus dRoid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus drOid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droId creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droiD creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid Creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid cReators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid crEators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creAtors ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creaTors ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatOs .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatoRs ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creatorS ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m Virus droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m vIrus droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viRus droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virUs droid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m viruS droid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus dRoid creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus drOid creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droId creators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droiD creators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid Creators ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid cReators ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid crEators .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creAtors ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creaTors ...")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatOs .")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus droid creatoRs ..")
	os.system("clear")
	slowprint("\x1b[1;91m[!]\x1b[00m virus Droid creatorS ...")
	os.system("clear")
	slowprint2("\033[41mVIRUS DROID CREATORS\033[00m")
	slowprint2("\x1b[00mOpening tools ...")
	os.system("python2 ~/Virus-droid-creator/Auth/Iqbalmh18/dog.pyc")

main() 
