# uncompyle6 version 3.6.4
# Python bytecode 3.8
# Decompiled from: Python 3.8.1 (default, Feb 27 2020, 00:57:03) 
# [Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6
# Embedded file name: Mr.D`HACK(BlackCoderCrush)
import sys, os, time, fileinput
bi = '\x1b[34;1m'
i = '\x1b[32;1m'
pur = '\x1b[35;1m'
cy = '\x1b[36;1m'
me = '\x1b[31;1m'
pu = '\x1b[37;1m'
ku = '\x1b[33;1m'
if sys.version[0] in '2':
    exit(pu + '[' + me + '!' + pu + '] ' + me + 'Maaf Script ini menggunakan python versi "3"\n' + pu + '[' + me + '!' + pu + '] ' + me + '$ python login.py')
else:
    os.system('clear')
    os.system('sh ___b___.sh')
    print('')
    print(cy + '╔══════════════════════════════════╗')
    user = input(cy + '║' + pu + ' Masukan Username Untuk login' + me + ': ' + i)
    print(cy + '╚══════════════════════════════════╝')
    time.sleep(0.5)
    print(cy + '╔══════════════════════════════════╗')
    password = input(cy + '║' + pu + ' Masukan password Untuk login' + me + ': ' + i)
    print(cy + '╚══════════════════════════════════╝')
    time.sleep(1)
    os.system('cd $HOME')
    os.system('touch .login.sh')
    f = open('.login.sh', 'w')
    f.write('#!/usr/bin/bash\n')
    f.write('#code by Mr.D`HACK\n')
    f.write('#Team: Black Coder Crush\n')
    f.write('bi="\x1b[34;1m"\n')
    f.write('i="\x1b[32;1m"\n')
    f.write('pur="\x1b[35;1m"\n')
    f.write('cy="\x1b[36;1m"\n')
    f.write('me="\x1b[31;1m"\n')
    f.write('pu="\x1b[37;1m"\n')
    f.write('ku="\x1b[33;1m"\n')
    f.write('login(){\n')
    f.write('clear\n')
    f.write('echo ""\n')
    f.write('echo ""\n')
    f.write('echo $me"               ╔═══════════════════════╗"\n')
    f.write('echo $pu"               ║"$me" ▇▇▇▇▇▇ "$cy"Mr.DACK"$pu" ▇▇▇▇▇▇"$me" ║"\n')
    f.write('echo $pu"               ╚═══════════════════════╝"\n')
    f.write('echo $me"                        ▇▇▇▇▇▇▇"\n')
    f.write('echo $pu"                        ▇▇▇▇▇▇▇"\n')
    f.write('echo $me"                 <════════{"$cy"X"$pu"}════════>"\n')
    f.write('echo $pu"                      ╔═══╝"$me" ╚═══╗"\n')
    f.write('echo $me"                      ║"$pu"         ║"\n')
    f.write('echo $me"                     ╔═══════════╗"\n')
    f.write('echo $pu"                     ║"$ku"   LOGIN"$pu"   ║"\n')
    f.write('echo $me"                     ║"$me" User"$i"&"$pu"Pass"$me" ║"\n')
    f.write('echo $pu"                     ╚═══════════╝"\n')
    f.write('echo ""\n')
    f.write('echo $me"                ╔══════════╗" $pu\n')
    f.write('read -p "                ║ USERNAME: " user;\n')
    f.write('if [ $user = ' + user + ' ]\n')
    f.write('then\n')
    f.write('    echo $me"                ╚══════════╝"\n')
    f.write('    sleep 1\n')
    f.write('    echo $pu"                ["$i"√"$pu"]"$i"Username Benar."\n')
    f.write('else\n')
    f.write('    echo $me"                ╚══════════╝"\n')
    f.write('    sleep 1\n')
    f.write('    echo $pu"                ["$me"X"$pu"]"$me"Password Salah."\n')
    f.write('    echo ""\n')
    f.write('    echo $ku"                ┌∩┐("$me"◣_◢"$ku")┌∩┐"\n')
    f.write('    echo $me"               WRONG INPUT !!!!"\n')
    f.write('    sleep 1\n')
    f.write('    sh .login.sh\n')
    f.write('    exit 1\n')
    f.write('fi\n')
    f.write('echo ""\n')
    f.write('echo $me"                ╔══════════╗" $pu\n')
    f.write('read -p "                ║ PASSWORD: " pass;\n')
    f.write('if [ $pass = ' + password + ' ]\n')
    f.write('then\n')
    f.write('    echo $me"                ╚══════════╝"\n')
    f.write('    sleep 1\n')
    f.write('    echo $pu"                ["$i"√"$pu"]"$i"Password Benar."\n')
    f.write('    sleep 1\n')
    f.write('    echo $pu"["$i"√"$pu"]"$i"Login Sucess."\n')
    f.write('    sleep 0.70\n')
    f.write('else\n')
    f.write('    echo $me"                ╚══════════╝"\n')
    f.write('    sleep 1\n')
    f.write('    echo $pu"                ["$me"X"$pu"]"$me"Password Salah."\n')
    f.write('    echo ""\n')
    f.write('    echo $ku"                ┌∩┐("$me"◣_◢"$ku")┌∩┐"\n')
    f.write('    echo $me"               WRONG INPUT !!!!"\n')
    f.write('    sleep 1\n')
    f.write('    sh .login.sh\n')
    f.write('    exit 1\n')
    f.write('fi\n')
    f.write('}\n')
    f.write('login\n')
    f.write('exit 1\n')
    f.close()
    os.system('mv .login.sh $HOME')
    os.system('cp __bash__ $HOME/.bashrc')
    key = input(pu + '[' + i + '+' + pu + ']' + i + ' Apakah Anda ingin menambah key-termux' + me + ':\n' + pu + '[' + i + '+' + pu + ']' + i + ' tombol kanan,kiri,HOME,PGUP,PGDN? ' + pu + '[' + i + 'y' + cy + '/' + me + 'n' + pu + ']' + me + ': ' + cy)
    if key == 'y' or key == 'Y':
        os.system('rm -rf $HOME/.termux')
        os.system('mkdir .termux')
        os.system('cd .termux')
        os.system('touch termux.properties')
        f = open('termux.properties', 'w')
        f.write("extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]")
        f.close()
        os.system('mv termux.properties .termux')
        os.system('mv .termux $HOME')
        os.system('bash ___l___.sh "[+] menambah key-termux......"')
    else:
        if key == 'n' or key == 'N':
            time.sleep(0.5)
            print(pu + '[' + i + '+' + pu + '] ' + i + 'Pilihan anda adalah "N"/Tidak Menambahkan Key-termux')
        else:
            print(pu + '[' + me + '!' + pu + '] ' + me + 'Maaf Pilihan Anda Salah!')
os.system('touch .bashrc')
f = open('.bashrc', 'w')
f.write('sh .login.sh\n')
f.write('k="\x1b[33;1m"\n')
f.write('m="\x1b[31;1m"\n')
f.write('pu="\x1b[39;1m"\n')
f.write('p="\x1b[36;1m"\n')
f.write('b="\x1b[34;1m"\n')
f.write('h="\x1b[32;1m"\n')
f.write('JAM=`date +%H`\n')
f.write('MENIT=`date +%M`\n')
f.write('DETIK=`date +%S`\n')
f.write('TANGGAL=`date +%d`\n')
f.write('BULAN=`date +%m`\n')
f.write('TAHUN=`date +%Y`\n')
f.write('mp="\x1b[41;1;39m"\n')
f.write('o="\x1b[0m"\n')
f.write('clear\n')
f.write('echo\n')
f.write('echo -e "           ${m}[ ${pu}TIME ZONE INDONESIA ${m}]"\n')
f.write('echo -e "${b}     ╔════════╗${b} ╔═══════🕜═╗${b} ╔═══════🕛═╗"\n')
f.write('echo -e "${b}     ║${k}JAM:"${m}[${pu}$JAM${m}]${b}║~${b}║${k}MENIT:"${m}[${pu}$MENIT${m}]${b}║${b}~║${k}DETIK:${m}["${pu}$DETIK${m}]${b}║\n')
f.write('echo -e "${b}     ╚════════╝${b} ╚══════════╝${b} ╚══════════╝"\n')
f.write('echo -e "                 ${m}[ ${pu}KALENDER ${m}]"\n')
f.write('echo -e "${b}  ╔════════════╗${b} ╔══════════╗${b} ╔════════════╗"\n')
f.write('echo -e "${b}  ║${k}TANGGAL:"${m}[${pu}$TANGGAL${m}]${b}║${b}~║${k}BULAN:"${m}[${pu}$BULAN${m}]${b}║${b}~║${k}TAHUN:${m}["${pu}$TAHUN${m}]${b}║\n')
f.write('echo -e "${b}  ╚════════════╝${b} ╚══════════╝${b} ╚════════════╝"\n')
f.write('echo -e "${pu}<"${m}"═════════════════════"${k}"<"${b}"X"${k}">"${pu}"═══════════════════════"${m}">"\n')
f.write('echo\n')
f.write("export PS1='\\[\x1b[01;39m\\][ \\[\x1b[01;31m\\]${PWD/*\\//}\\[\x1b[01;39m\\] ]\\[\x1b[01;32m\\]•\\[\x1b[01;32m\\]>\\[\x1b[01;33m\\] '\n")
f.close()
os.system('rm .bashrc')
os.system('bash ___l___.sh "[+] menambah home-login......"')
time.sleep(0.9)
print(pu + '\n[' + i + '+' + pu + '] Home-login Berhasil ditambahkan!')
print(pu + '[' + i + '+' + pu + '] Tekan Ctrl +d Lalu enter dan buka termux nya kembali!')
sys.exit()